### ISSUE TITLE
Mobile navigation 

### ISSUE THREAD

**Issue by danielo515** [iced-rs/book#7]
Hello, and thank you very much for putting the time in writing a book.
I wanted to take a look from my mobile, but sadly the menu is not navigable (links do nothing for some reason) and there is no "next page" at the bottom of each page, wich is another common way to navigate on mobile.
I think it will be cool if those could be fixed.
Regards

**Comment by wiiznokes** [comment]
the book is generated thank to [mdbook](https://github.com/rust-lang/mdBook). It take .md files and create a website. Also, this it because pages are not yet create (still TODO).

**Comment by hecrj** [comment]
The book isn't empty anymore. Closing!
